GET http://localhost:3001/api

###
GET http://localhost:3001/api/notes

### 
GET http://localhost:3001/api/notes/699cfbf0026e8346676c810d

### 
DELETE http://localhost:3001/api/notes/699cfbf0026e8346676c810d

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "test",
    "important": true
}

###
PUT http://localhost:3001/api/notes/699cfbf0026e8346676c810d HTTP/1.1
content-Type: application/json

{
    "content": "update test",
    "important": false
}